---
name: cmpsc-100-fall-2018-practical8
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        practicaleight/DisplaySymbols.java:
            --single 8 --language Java
            --multi 4 --language Java
            --fragment "println(" --count 4
            --fragment "TODO" --count 0 --exact
# --> check the number of commits beyond a threshold
--commits 5
# --> check that the program executes and produces 4 lines of output
# --> check that the output contains a fragment
--command "gradle -q --console plain run" --executes
